const { JSDOM } = require("jsdom");
const BASE = "http://127.0.0.1:" + (process.env.PORT || "8799");
(async () => {
  const html = await (await fetch(`${BASE}/video/export`)).text();
  const dom = new JSDOM(html, { runScripts: "outside-only", url: `${BASE}/video/export`, pretendToBeVisual: true });
  const { window } = dom;
  window.fetch = () => Promise.resolve({ok: false});
  window.URL.createObjectURL = () => "blob:x"; window.URL.revokeObjectURL = () => {};
  window.eval(await (await fetch(`${BASE}/static/app.js?t=5`)).text());
  window.eval([...window.document.querySelectorAll("script:not([src])")].map(s => s.textContent).join("\n"));
  const doc = window.document, form = doc.getElementById("op");
  const start = form.querySelector('[name="edits_trim_start"]'), end = form.querySelector('[name="edits_trim_end"]');
  let probe = null;
  const realCreate = doc.createElement.bind(doc);
  doc.createElement = tag => {const el = realCreate(tag); if(tag === "video") probe = el; return el;};
  window.fitTrimRange(form, {type: "video/mp4"});
  Object.defineProperty(probe, "duration", {value: 236.398});
  probe.onloadedmetadata();
  console.log("max floored to duration:", end.max === "236.3", "(got", end.max + ")");
  console.log("untouched handles stay clean:", !start.dataset.dirty && !end.dataset.dirty);
  const data = {deleted: []};
  const fd = {delete: n => data.deleted.push(n), append: () => {}};
  form.querySelectorAll("input[data-range]").forEach(range => {if(!range.dataset.dirty) fd.delete(range.name);});
  console.log("trim omitted from submission:", data.deleted.includes("edits_trim_start") && data.deleted.includes("edits_trim_end"));
  end.dataset.dirty = "1"; end.value = "100";
  window.fitTrimRange(form, {type: "video/mp4"});
  Object.defineProperty(probe, "duration", {value: 236.398});
  probe.onloadedmetadata();
  console.log("user-touched handle survives refit:", end.dataset.dirty === "1" && end.value === "100");
})();
